### ISSUE TITLE
Trying desperately to get HomeBridge talking with smart things.

### ISSUE THREAD

**Issue by rkcolorado** [pdlove/homebridge-smartthings#109]
I keep getting an an error that reads "There was a problem authenticating with smart things ". I checked my JSON files many times to no avail. 
 Has anyone else had this problem and solved it? Thanks in advance! I've spent hours trying to figure out what I am doing wrong, but there just isn't a whole lot of in depth literature out there on troubleshooting. 
![screen shot 2016-10-20 at 7 49 30 am](https://cloud.githubusercontent.com/assets/22529993/19562506/d377515a-9699-11e6-9eda-e76587d1ef90.png)

**Comment by RLovelett** [comment]
@rkcolorado I can say that I am having the same problem. Is there a `curl` request that I could make that would allow me to test that I have properly configured my `app_id` and `access_token`?

**Comment by RLovelett** [comment]
@rkcolorado I have come up with a solution for myself. Perhaps it will help you...

The `app_url` field was different than the default. It was: `https://graph-na02-useast1.api.smartthings.com:443/api/smartapps/installations` instead of the `https://graph.api.smartthings.com:443/...` one.

I ended up debugging the node app and using cURL to figure out the format of the requests. Then just started playing with settings until I got a correct one. YMMV.

**Comment by rkcolorado** [comment]
@Rlovelett Thank you for the suggestion, I'm going to give that a shot tomorrow!

**Comment by hageson** [comment]
I see only one difference between your JSON file and mine.  Mine has the following 'platform' property value:

		"platform": "homebridge-smartthings.SmartThings",

I have no idea whether this is relevant but I don't get the error you're getting.

**Comment by rkcolorado** [comment]
Thanks for getting back to me @hageson. I figured I must have been doing something else wrong so I wiped the raspi and started over. After a bit of fiddling it is working! I'm really enjoying this now.
