### ISSUE TITLE
Hub V1 or v2 for Direct?

### ISSUE THREAD

**Issue by jesseking3** [pdlove/homebridge-smartthings#140]
Confirming that direct communication work with both hub v1 and v2? 

On v1 - In log, seeing 
Direct Connect is listening on 192.168.x.x:8000

But not  - SmartThings Hub Communication Established

Should we expect to see
SmartThings Hub Communication Established ?

**Comment by pdlove** [comment]
I'm not sure? Nothing in the API says that the commands are hub v2 specific. I'll ask my smartthings contact. Do you have a firewall on your pc that might block inbound port 8000 from the hub?

**Comment by pdlove** [comment]
I have confirmation that it should be working on the v1 hub. Did you update your SmartApp to version 0.5.2?

**Comment by jesseking3** [comment]
Thanks for checking. I'll update everything tonight and recheck!

**Comment by jesseking3** [comment]
I have to mention that this has version has greatly reduced the amount of bandwidth as well as flows to graph.api.smartthings.com. Its night and day. So It must be working direct now.

I can see why smartthings requested this change.

![image](https://cloud.githubusercontent.com/assets/13879178/22513586/ac92b89a-e86a-11e6-9b6c-ceff61efb25a.png)

**Comment by pdlove** [comment]
The main reason they asked for it is because they have infrastructure changes coming up and this makes it easier on their API infrastructure. It sounds like same awesome things might be coming down the pipe.

Also, when I wrote it, I used their posted rate limits as guidelines for how real-time I could get it so I was bumping limits. 😄
