### ISSUE TITLE
Unable to add devices to JSON Complete API SmartApp

### ISSUE THREAD

**Issue by stealth658** [pdlove/homebridge-smartthings#173]
I had homebridge-smartthings working, but recently, I was having some issues with my homebridge setup, so I decided to start everything from scratch. Now, after installing the JSON Complete API smartapp, I am unable to add my devices and have them stick. I choose my devices within the smartapp (from Most Devices, Sensor Devices, and All Switches), when I press Done and then go back to the app, all the devices get unchecked as if I didn't choose them. And they don't show up in the homebridge log.

I'm trying to set up the app with 3 z-wave dimmer switches.

**Comment by burtamcgna** [comment]
This is confusing people because once you click "done" it is actually installing this SmartApp on your Device.  If you go through the process again, it will install another JSON on your device and you could end up with several of the same apps installed, each with it's own unique APP_ID and "Access_id"

Instead of staying in the "MarketPlace > Smart Apps area and clicking the JSON again, you need to go to:  Automation > SmartApps

Here you will see the JSON loaded on your device and when you open the JSON here you will see all of the devices you selected previously and be able to add additional devices. You can also add a "Label" to this JSON and call it something else.

In theory, you could have multiple versions of the JSON installed and each using a separate app_id and access_key to control different things.  I am not sure why you would want to, but you could.  For each JSON on your device, you would have to add a separate item to the Homebridge "config.json" with each unique app_id, URL, access_id

**Comment by stealth658** [comment]
Thank you so much for the thorough explanation! Helped me get everything back up and running in no time.
