### ISSUE TITLE
Input for all types

### ISSUE THREAD

**Issue by pdlove** [pdlove/homebridge-smartthings#2]
Does anyone know how to do a single input that covers all types in the groovy file? Even  better would be one to automatically install on new devices.

**Comment by alisdairjsmyth** [comment]
I don't think there is an existing mechanism that enables you to get all devices of all types into a single input within the ST API.  I tried "*", "capability.switch, capability.thermostat". Within the ST environment, this model of identifying devices by a specific capability makes sense - as a SmartApp is designed to work with specific device types.

As to automatically installing devices - I don't think this is possible either.  Devices need to be associated to a SmartApp by the user for a SmartApp to be able to interact with it.  Since Homebridge is connecting to SmartThings via a SmartApp, only those devices associated by the user to the SmartApp can be interacted with via Homebridge.  Consequently I doubt it would be possible for Homebridge to automatically start interacting with a ST connected device without it first being associated to the SmartApp.
In my own personal case, I am okay with this as I am going to use ST as a ZigBee/ZWave Gateway and utilise native plugins where they exist (e.g. LiFX and Sonos).  So I will use this selection mechanism that is present within the SmartApp to exclude such devices.

**Comment by pdlove** [comment]
That is roughly what I experienced as well. My wife is on an Android phone, so I was trying to get everything in one app for her while still extending to HomeKit.
I'm probably going to do the same as you and then figure it out from there. I'm actually dreaming up a web interface for home bridge that would plug into it and expose things to Android. Alternatively, I considered simply making an Android app that connected with the HomeKit protocol, but I think that would incur the wrath of Apple.

**Comment by pdlove** [comment]
I found this is possible by using the refresh capability. Basically, every device has a refresh capability
