### ISSUE TITLE
Updating code from repo

### ISSUE THREAD

**Issue by coolcom** [pdlove/homebridge-smartthings#30]
When there are updates to the code, and I update the code from the repo, and publish those changes...do I need to do anything else?

Thanks

**Comment by pdlove** [comment]
As far as the SmartApp is concerned, when you publish, you're good.
If in double, you can tap the app in smartthings and verify the version number there. The current version is 0.3.5. I will add the current version number to the top of the readme.md file so that you can reference that to make sure you are the most up to date. I have some upcoming changes to it that will put it at version 0.4, but I don't expect many updates to it after that.

**Comment by coolcom** [comment]
Great, thank you. I see I am on 0.3.5 and putting the version on readme.md would be excellent. Thank you!

Sorry, I am new to Github, I see you can add labels.
