### ISSUE TITLE
Lost connectivity after plugin update 

### ISSUE THREAD

**Issue by rickybloomfield** [pdlove/homebridge-smartthings#47]
I've noticed that I've lost connectivity with homebridge after the last few times I've updated this plugin via npm. Homebridge is still running just fine, but the devices are unreachable. The only way to get it back is to delete the "persist" folder AND change the "username" in the config.json file.

Any suggestions for this? Every time this happens I have to remove and re-add the homebridge accessory, which means I have to go through and manually assign each device to the appropriate room again. Obviously, this is somewhat tedious!

I wasn't sure if this was a homebridge issue or specific to this plugin (since it has only happened when updating this plugin).

**Comment by KumarMudedla** [comment]
Mine fixed by doing the same, after updating to latest version two days back it's keep going unreachable ( it tried deleting persist folder and re adding the device but it will go unreachable in few hours) finally renaming the Homebridge to "Homebridge1" in the config.json fixed the issue.  I did that last night and it is still working I hope it will stay this way now.

**Comment by pdlove** [comment]
Try this with plugin version 0.4.4. I've corrected a lot on the error handling. You'll still get the connection errors because that is all smart things being an issue.... but it shouldn't cause home bridge to crash as it has been doing.

**Comment by pdlove** [comment]
I'm moving all discussion to issue #58. I was able to iron out one major issue last night an just released that as 0.4.6.
