### ISSUE TITLE
homebridge-smartthings 0.4.0+ Other npms versions Status

### ISSUE THREAD

**Issue by pdlove** [pdlove/homebridge-smartthings#50]
We've had so many issues that I want to get some version information from people who are working and Not. Please post in here only the version information and if it is working. Thank you for your help as we try to determine why this latest update works well for many people and doesn't work at all for others.
Even with the issue of leaving/returning making some devices vanish I'm calling it working great because that seems to be an IOS problem as I noticed my native homekit devices were doing the same thing.

Status: Working Great with no timing tweaks.
"node -v" - v4.2.1
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5
"npm view homebridge-smartthings version" - 0.4.3

OSX 10.11.3

**Comment by coolcom** [comment]
Status: Not working at all. Even though Homebridge loads all my ST devices and gives me the code, my phone (6S Plus, 9.2.1) refuses to see it. Previously, it would see it, I could control the devices, etc. but if I would leave the network and come back, everything would be "not reachable."

node -v - v5.6.0
npm view homebridge version - 0.2.19
npm view hap-nodejs version - 0.2.5
npm view homebridge-smartthings version - 0.4.3

Ubuntu 14.0.4.4 LTS Linux version 4.2.0-30-generic (buildd@lgw01-42)

**Comment by coolcom** [comment]
I can try installing on my Mac. Does this look about right for installation?

https://www.reddit.com/r/homeautomation/comments/3ysgbb/homebridge_how_to_on_mac/

**Comment by rickybloomfield** [comment]
Status: Working for past 3 days with no timing tweaks. Today I just got a bunch of errors, although things still seem to be working. At first I was confused at all the random IP addresses (107.20.201.51, 54.243.74.147, 174.129.9.165), but then I realized that they are the IP addresses for the SmartThings website. Errors can be seen here: [Errors.txt](https://github.com/pdlove/homebridge-smartthings/files/143718/Errors.txt)

"node -v" - v4.2.4
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5
"npm view homebridge-smartthings version" - 0.4.3

Running on Raspberry Pi 2 with latest Raspian OS.

**Comment by coolcom** [comment]
Tried on node v4.2.1 and Ubuntu 15.10. Unable to add to homekit (does not even appear), but all the ST devices are added. I don't think this is an issue with the ST plugin.

**Comment by coolcom** [comment]
I installed all this on my Mac and same thing. It loads homebridge, all the ST devices, gives me the code, but not one of my 3 Homekit apps will see it. I think I am cursed and it is not an issue with the homebridge-smartthings plugin, in my case.

**Comment by humac** [comment]
@coolcom are you using the iOS 9.3 Beta i think there is a know issue

**Comment by coolcom** [comment]
I am on 9.2.1 and am currently updating to the latest 9.2.1 (they put out an update only available via iTunes).

Something is up, because I cannot even add my real HomeKit compatible Ecobee3. I've erased my "Home" from my phone many times, created new ones, etc. to no avail.

**Comment by coolcom** [comment]
Well, I saw it when I typed the message, but when I tapped on it, it wouldn't respond. I quit the app, restarted, and now it sees nothing and we are back to where I was before. :(

**Comment by coolcom** [comment]
Ok- my Airport was having some major issues. Rebooted that and I am back in business (somewhat).

**Comment by coolcom** [comment]
I finally have a working setup, sorry for the messages and then deletions, etc. I updated my original comment. Good work @pdlove.

**Comment by Slepperpon** [comment]
Just crashed today after 10 days would not start back up but then it did and crashed 

node -v 4.1.1
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5
"npm view homebridge-smartthings version" - 0.4.3

Running on Raspberry Pi 2 with latest Raspian OS.

**Comment by mishakim** [comment]
"node -v" - v4.2.2
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5
"npm view homebridge-smartthings version" - 0.4.3

Raspberry PI B latest Raspbian

Status: seems to be working, but I see my log early this morning was flooded with this:
`Feb 25 03:22:27 raspberrypi homebridge[23338]: error at req:  { [Error: getaddrinfo ENOTFOUND graph.api.smartthings.com graph.api.smartthings.com:443]
Feb 25 03:22:27 raspberrypi homebridge[23338]: code: 'ENOTFOUND',
Feb 25 03:22:27 raspberrypi homebridge[23338]: errno: 'ENOTFOUND',
Feb 25 03:22:27 raspberrypi homebridge[23338]: syscall: 'getaddrinfo',
Feb 25 03:22:27 raspberrypi homebridge[23338]: hostname: 'graph.api.smartthings.com',
Feb 25 03:22:27 raspberrypi homebridge[23338]: host: 'graph.api.smartthings.com',
Feb 25 03:22:27 raspberrypi homebridge[23338]: port: '443' }`

which eventually ended with this:
`Feb 25 04:13:24 raspberrypi homebridge[23338]: error at req:  { [Error: connect EHOSTUNREACH 174.129.9.165:443]
Feb 25 04:13:24 raspberrypi homebridge[23338]: code: 'EHOSTUNREACH',
Feb 25 04:13:24 raspberrypi homebridge[23338]: errno: 'EHOSTUNREACH',
Feb 25 04:13:24 raspberrypi homebridge[23338]: syscall: 'connect',
Feb 25 04:13:24 raspberrypi homebridge[23338]: address: '174.129.9.165',
Feb 25 04:13:24 raspberrypi homebridge[23338]: port: 443 }`

and then nine hours later, Homebridge crashed and restarted after this:
`Feb 25 17:05:18 raspberrypi homebridge[23338]: /usr/local/lib/node_modules/homebridge-smartthings/index.js:76
Feb 25 17:05:18 raspberrypi homebridge[23338]: } else if (myList.error) {
Feb 25 17:05:19 raspberrypi homebridge[23338]: ^
Feb 25 17:05:19 raspberrypi homebridge[23338]: TypeError: Cannot read property 'error' of undefined
Feb 25 17:05:19 raspberrypi homebridge[23338]: at /usr/local/lib/node_modules/homebridge-smartthings/index.js:76:30
Feb 25 17:05:19 raspberrypi homebridge[23338]: at /usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
Feb 25 17:05:19 raspberrypi homebridge[23338]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:27)
Feb 25 17:05:19 raspberrypi homebridge[23338]: at emitNone (events.js:72:20)
Feb 25 17:05:19 raspberrypi homebridge[23338]: at IncomingMessage.emit (events.js:166:7)
Feb 25 17:05:19 raspberrypi homebridge[23338]: at endReadableNT (_stream_readable.js:905:12)
Feb 25 17:05:19 raspberrypi homebridge[23338]: at doNTCallback2 (node.js:441:9)
Feb 25 17:05:19 raspberrypi homebridge[23338]: at process._tickCallback (node.js:355:17)
Feb 25 17:05:19 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Feb 25 17:05:19 raspberrypi systemd[1]: Unit homebridge.service entered failed state.`

It restarted with no errors and claims to be running fine, but it not reachable in HomeKit apps. May be due to problems with OpenHab, will troubleshoot more after I get kids in bed

**Comment by mishakim** [comment]
I got homebridge to complete startup by disabling a component of openhab that seemed to be stalling that service, but the HomeKit apps claimed nothing is connected, while the log showed requests for updates of components getting through. Deleting and reading the homebridge accessory worked, without any of the more extreme measures (delete persist, flush HomeKit config, etc)

**Comment by axemann** [comment]
"node -v" - v5.6.0
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5
"npm view homebridge-smartthings version" - 0.4.3

Running in a FreeNAS jail (FreeBSD 9.3), but I originally tried it under Ubuntu 14.04 with the same results as below...

Can add Homebridge and see devices, but a couple show as missing after about 15 minutes, and slowly over time things get worse until nothing responds. I can nuke the persist folder contents, reset HomeKit, and re-add Homebridge and the cycle repeats. I just picked up an ATV3 to try to get remote access to work, but if it's pooping the bed while I'm still at home remote access is moot.

**Comment by coolcom** [comment]
@axemann FWIW, I had zero success with Ubuntu (it was running in a VM). Both 14.04 and 15.10. You would not believe how many different versions of node I tried. I installed it on my Mac, and has been rock solid since. ATV3 remote access works perfectly.

**Comment by axemann** [comment]
@coolcom I may have to give that a shot if I can ever get OSX running on my ESXi box...

**Comment by pdlove** [comment]
I have it running flawlessly on my raspberry pic under raspbian. I'll install the latest Ubuntu so I can get the problems y'all have.

**Comment by rickybloomfield** [comment]
Mine was running great on my RPi2 (Raspbian) for several days, then konked out yesterday. Not sure if it had something to do with the SmartThings outage or not. A restart didn't work to fix it. I had to remove the persist folder, etc., and re-add Homebridge from scratch...

**Comment by mishakim** [comment]
Everything seems fine this morning, not sure what yesterday's issues were, I'll see how it goes today. My weekend project is to update to OpenHab 2, and if that works I may move that to its internal HomeKit code instead of homebridge, simplifying the issues for the smartthings plugin.

**Comment by mishakim** [comment]
Got home tonight and Homebridge is down, last thing in the log is 7 hours ago:

`Feb 26 12:50:30 raspberrypi homebridge[378]: error at req:  { [Error: connect ETIMEDOUT 174.129.9.165:443]
Feb 26 12:50:30 raspberrypi homebridge[378]: code: 'ETIMEDOUT',
Feb 26 12:50:30 raspberrypi homebridge[378]: errno: 'ETIMEDOUT',
Feb 26 12:50:30 raspberrypi homebridge[378]: syscall: 'connect',
Feb 26 12:50:30 raspberrypi homebridge[378]: address: '174.129.9.165',
Feb 26 12:50:30 raspberrypi homebridge[378]: port: 443 }`

Restarting Homebridge fixed it, for now.
Given the Amazon AWS IP address, I'm guessing it's related to SmartThings's platform issues, though they claim everything's back to green at status.smartthings.com 

What's mainly annoying is that homebridge didn't know it had failed, so systemd didn't restart it.

**Comment by KumarMudedla** [comment]
I had below versions and after upgrading to 0.4.1\0.4.3 I see the devices keep going unreachable and tried and tried and gave up and using 0.3.5 with no issues.
"node -v" - v5.6.0
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5

After seeing that latest version working fine for few of you with node version 4.2.1/4.2.4 I have downgraded node to 4.2.4 and reinstalled Homebridge and homebridge-smartthings again and tried with two different iPhones (9.2.1) it was working fine for some time and then going unreachable, tried many times each time I am changing the homebridge name and deleting the persist folder and re-adding the homebridge and the same issue again and again.

so going back to 0.3.5 for now as that works for me.

**Comment by axemann** [comment]
@KumarMudedla and all:  I just wanted to confirm that I reverted to version 0.3.5 of the plugin and everything seems stable except for device updates, which seem to work at random (at this point).

**Comment by humac** [comment]
Status: NOT Working (Works for a few hours but then I loose all devices requires restart of services to bring all devices back)
OS X El Capitan (10.11.3)
"node -v" - v4.2.1
"npm view homebridge version" - 0.2.19
"npm view hap-nodejs version" - 0.2.5
"npm view homebridge-smartthings version" - 0.4.3

HomeKit Device iPhone 6s
iOS 9.3 Beta

**Comment by coolcom** [comment]
Update for me:
It works great for 2 days, but then stops working. If I stop and start homebridge, I get duplicate entries of all my devices in Homekit. So I remove persist, change the name, and re-add. It works for a couple days again.

Where are the log files located that I could perhaps take a look at? I'm on OS X.

**Comment by humac** [comment]
This is the last error I see in my error logs: 
Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 381dd3b1-eb0c-438f-8fd9-aa0d239e6fbd
    at Bridge.Accessory.addBridgedAccessory (/Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/A$
    at Server.<anonymous> (/Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge/lib/server.js:231:24)
    at /Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge-smartthings/index.js:104:4
    at /Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge-smartthings/index.js:81:5
    at /Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:93:13
    at IncomingMessage.<anonymous> (/Users/huynguyen/.nvm/versions/node/v4.2.1/lib/node_modules/homebridge-smartthings/lib/smartthingsapi.js:46:2$
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ETIMEDOUT
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
events.js:141

Now I have homebridge running as a launchDaemon and it's set to reload if it crashes, maybe when it tries to reload it's causing problems which is why I see this error.  @coolcom since i'm using a launchDaemon i tell it where to output the errors, not sure where it goes by default.  Before I was using @pdlove plugin and I was using the legacy plugin this was the method I used to keep the service alive and worked well for me for a few weeks on end.  But maybe with this version I need to find a different way to relaunch the services when it does crash, or figure out why it's crashing in the first place.  I'm going to disable options for the launchDaemon to restart and see what errors I get from there.

**Comment by coolcom** [comment]
Note: I am not using launchDaemon and haven't really needed as I don't have any issues with it crashing and stopping. I just have issues with the Homekit not recognizing/reaching any of my devices.

**Comment by surfous** [comment]
Status: NOT working. Works for a little while after removing persist directory and restarting homebridge, removing home from HomeKit app and re-adding Homebridge accessory. After ~1hr, homebridge and all subordinate accessories go *poof* (i.e., no longer appear in any HomeKit app).

Things that do not work to recover:
* Restarting homebridge
* reboot rpi
* remove persist directory & restart homebridge
* remove persist directory & reboot rpi
* change bridge username in config.json & restart homebridge
* change bridge username in config.json & reboot pi

To get my homebridge devices back, I do ALL of the following:
* stop homebridge
* remove persist
* change bridge username in config.json
* start homebridge
* re-add homebridge accessory to HomeKit
* re-populate rooms with "new" homebridge devices

rpi 2 model B
Ubuntu 15.10 (GNU/Linux 4.1.15-v7+ armv7l) (Ubuntu MATE 15.10)
"node -v" - v5.7.0
"npm view homebridge version" - 0.3.0
"npm view hap-nodejs version" - 0.2.6
"npm view homebridge-smartthings version" - 0.4.3
"npm view homebridge-liftmaster version" - 0.1.2
"npm view homebridge-harmonyhub version" - 0.1.1

HomeKit device iPhone 6 plus
iOS version 9.2.1

Note, homebridge-smartthings is not my only home bridge plugin, and ALL my accessories under homebridge are affected, not just the home bridge-smartthings ones. Therefore, is this (well, my variant, at least) a homebridge-smartthings issue, or really a homebridge issue? 

I've gotten my devices added back again, and I'll check the log for errors if/when my homebridge setup flatlines again.

**Comment by pdlove** [comment]
I still think this is insane because I've been running fine for 2 weeks now without restarting.
I'll be updating tonight with much better error trapping.

**Comment by surfous** [comment]
It's more insane than you might imagine. 

When I'm running homebridge, I've noticed that my wireless network gets flattened periodically, requiring a restart of my router (Apple Time Capsule from 2012 or so). Then my Apple devices start "counting" - adding a serial number after the device name. 

I've seen this same behavior with OS X Yosemite  when Apple had switched out mdnsresponder for disvoveryd to handle Bonjour. As of OS X 10.10.4, Apple switched back to mdnsresponder. 

I suspect that avahi is the culprit here, causing this situation to reappear, however homebridge isn't able to "count up" a new device name after the network is restarted. This would explain why those running homebridge on OS X don't see the problem. 

Since you don't see this problem on raspbian, I'm curious what our respective versions of avahi-daemon are. I'm not at home to check right this moment, but I'll report what I find. If there's no version difference, maybe a config difference? 

Worst case, I rebuild my pi with raspbian. 



--
Kevin Shuk
surf@surfous.com

**Comment by humac** [comment]
I'm running on OS X and it's not stable at all. All my devices from the plugin disappear after a couple hours or less. My homebridge-netatmo plugin seems fine tho and I can see those devices still. When the failure occurs it's seems my smartthings plugin and HarmonyHub plugin seem to cause those devices to disappear.  If i restart homebridge everything works again...

**Comment by humac** [comment]
Correction even my netatmo devices fail but they stay in HomeKit they just don't respond.  Smarttings and HarmonyHub devices disappear completely. Until I restart

**Comment by coolcom** [comment]
I'm on OS X, it runs flawless for ~36 hours, and then all the devices disappear from Homekit. There are only a few timeout errors, and those timestamps (installed homebridge--log via npm for timestamps) indicate that after the error occurred, I was able to verify everything working. It has since stopped working (all disappeared), and there have been no timedout or other errors after the previous mentioned.

That might be confusing...

Last error I see was yesterday afternoon. Yesterday evening it was working fine (AFTER the timeout). This morning, all devices are gone and not working.

**Comment by pdlove** [comment]
I'm moving all discussion to issue #58. I was able to iron out one major issue last night an just released that as 0.4.6.
