### ISSUE TITLE
Does this plugin work with smartthings motion sensors?

### ISSUE THREAD

**Issue by garywkfung** [pdlove/homebridge-smartthings#73]
Before I commit to making the purchase of a smartthings hub and kit, I want to make sure that a motion sensor can work with this plugin? 

In other words, can I create HomeKit triggers based on the action or idle time of the motion sensor?

**Comment by pdlove** [comment]
Yes, but I recommend against it due to lag in HomeKit. I use the triggers in SmartThings for instantly turning on a light. When phone is unlocked, HomeKit triggers will fire on a motion detector in a half second or less. With the phone locked, it takes over 5 seconds. If I'm not at home and my wife trips it, it takes 30 seconds plus. Some people report this isn't the case for them. But that is a HomeKit problem, not a smartthings or homebridge issue. To be clear, I'm suggesting using the function in smartthings to trigger when you can. Here's a simple how to on HomeKit in general http://www.macrumors.com/guide/homekit-101-getting-started-beginners/

Here's a guide on setting up triggers using the Eve app which is my preferred HomeKit app: https://blog.elgato.com/new-eve-1-5-fully-supports-homekit-event-based-triggers/

**Comment by pdlove** [comment]
I'll get my HomeKit synced back up tomorrow and put together a simple guide and see if it still has the delay problem.

**Comment by garywkfung** [comment]
Thanks for your help, I already have homekit and triggers working in my whole house. I just want add motion sensor to my home system. Can you explain how the trigger will work? Does homekit read it as a variable? Like motion = yes in the Eve app? 

Also, I dont see how a trigger system like that can be invoked based on inactivity. Like if no motion is detected for 30 min or more.
